name: TradeSystem
author: CodingAir
version: "${project.version}"
description: A beautiful way to trade with other players.
main: de.codingair.tradesystem.spigot.TradeSystem
softdepend: [Vault, Essentials, PlaceholderAPI, TokenManager, GriefDefender]
api-version: "1.13"

permissions:
  tradesystem.notify:
    default: op
  tradesystem.motify:
    default: op
  tradesystem.log:
    default: op
  tradesystem.trade:
    default: op
  tradesystem.trade.initiate:
    default: op
  tradesystem.*:
    children:
      tradesystem.notify: true
      tradesystem.motify: true
      tradesystem.log: true
      tradesystem.trade: true
      tradesystem.trade.initiate: true